### ISSUE TITLE
Add Fusion Annotator workflow

### ISSUE THREAD

**Issue by jharenza** [d3b-center/OpenPBTA-workflows#3]
The workflow for annotating Arriba calls is missing, as far as I can tell (not in RNA-Seq workflow). 

@migbro can you add please?

**Comment by migbro** [comment]
hmmm, should I just update the RNAseq workflow to the one that covers all that is done that I think is equivalent? so, instead of another workflow, just put this one in say:
https://github.com/kids-first/kf-rnaseq-workflow/tree/v2.4.2

**Comment by jharenza** [comment]
I was looking at this earlier - I think adding https://github.com/kids-first/kf-rnaseq-workflow/blob/v2.4.2/tools/fusion_annotator.cwl and keeping it separate just in case there were any version changes of anything in the rest of RNA-Seq we may not want to add

**Comment by migbro** [comment]
Hmm, yeah, so, if in OpenPBTA, you formatted the stuff using something else, then yeah, I can use just that tool. Otherwise, the annoFuse workflow (which now gets run as a subworkflow within RNAseq), looks like this: https://github.com/kids-first/kf-rnaseq-workflow/blob/v2.4.2/workflow/kfdrc_annoFuse_wf.cwl
So you'll see that it gets formatted first, then fed into fusion_annotator

**Comment by jharenza** [comment]
We did the formatting here without annofuse, before it became a package!
